"""modules/kids/babel_strings.py — Dummy file exposing dynamic DB & dictionary strings to PyBabel."""
from flask_babel import lazy_gettext as _l

# ── Module Names & Descriptions ──
_l("Rede de computadores")
_l("A teia mundial, DNS, HTTP/HTTPS e pacotes de dados")
_l("Sistemas Operacionais")
_l("Comandos mágicos, terminal Linux e permissões de arquivos")
_l("Programação")
_l("Lógica de programação, variáveis, condicionais e Python")
_l("Security")
_l("Tríade CIA, senhas fortes, phishing e firewalls")
_l("Inglês para Cyber")
_l("Vocabulário técnico, comandos em inglês e man pages")

# ── Lesson Titles & Subtitles ──
_l("O que é a Internet?")
_l("A teia gigante que conecta o planeta")
_l("O que é um Endereço IP?")
_l("O CEP e RG de cada máquina conectada")
_l("O GPS da Web: DNS")
_l("Como o navegador acha sites sem saber números")
_l("O Carteiro (HTTP/HTTPS)")
_l("Cartas abertas vs cofres blindados criptografados")
_l("O Radar de Rede")
_l("Comandos essenciais: ping, ip e ifconfig")

_l("O Cérebro do Computador")
_l("O que é um Sistema Operacional e seus papéis")
_l("A Caverna do Terminal")
_l("Introdução ao Linux e comandos diretos no shell")
_l("Navegando no Escuro")
_l("Comandos essenciais: pwd, ls, cd e mkdir")
_l("As Chaves do Reino")
_l("Permissões de arquivos (r, w, x) e o comando chmod")

_l("A Receita de Bolo")
_l("Lógica de programação e passos ordenados")
_l("Caixas e Etiquetas")
_l("Variáveis, tipos de dados e strings na memória")
_l("O Semáforo (If/Else)")
_l("Condicionais e decisões baseadas em verdadeiro/falso")
_l("A Magia do Python")
_l("Seu primeiro script e comandos reais de automação")

_l("O Triângulo Mágico (Tríade CIA)")
_l("Confidencialidade, Integridade e Disponibilidade")
_l("A Chave da Porta")
_l("Senhas fortes, proteção contra força bruta e 2FA")
_l("O Pescador de Dados (Phishing)")
_l("Identificando mensagens falsas e engenharia social")
_l("Os Guardas do Castelo")
_l("Firewall perimetral e antivírus no disco")

_l("O Alfabeto do Hacker")
_l("A origem em inglês de ls, cd, cat e grep")
_l("Palavras que Assustam")
_l("Desmistificando Bug, Exploit, Payload e Hash")
_l("Lendo as Instruções")
_l("Dominando man pages e a flag --help no terminal")
_l("Falando com o Mundo")
_l("Relatórios técnicos, PoCs e disclosure responsável")

# ── Daily Quests ──
_l("Conclua 1 Lição na Trilha")
_l("Acerte 3 Perguntas de Quiz")
_l("Estude Comandos no Terminal")

# ── Academy Funnel Targets ──
_l("Lab 02: Command Injection")
_l("Pratique execução de comandos no Linux real!")
_l("Lab 03: CSRF & Requisições Web")
_l("Teste requisições HTTP reais e tokens de segurança!")
_l("Lab 07: SQL Injection")
_l("Explore lógica e consultas de banco de dados!")
_l("Lab 01: Brute Force")
_l("Quebre senhas fracas e domine autenticação!")
_l("Documentação Oficial")
_l("Consulte manuais e referências técnicas em inglês!")
_l("DUNO Academy")
_l("Laboratórios práticos")
